name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        working-directory: ./app
        run: npm install

      - name: Run tests
        working-directory: ./app
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-docker-app:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-docker-app:latest
